=== mojazAli/100DaysLearningChallenge/Day 23 XML/studentRecordsSchema.xsd
<xs:schema xmlns="http://www.example.com/studentRecordsSchema">

	<xs:element name="studentRecords">
		<xs:complexType>
		
			<xs:element name="student">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string">
						<xs:element name="age" type="xs:integer">
						<xs:element name="id" type="xs:integer">
						<xs:element name="contact" type="xs:string">
					</xs:sequence>
				</xs:complexType>
			</xs:element>

		</xs:complexType>
	</xs:element>

</xs:schema>

=== mojazAli/100DaysLearningChallenge/Day 23 XML/studentRecords.xml
<!-- 
	* XML stands for Extensible Markup Language, that provides
	rules to define any data. 
 	* XML deos not have any pre-defined tags. 
 	* These tags are created by XML document author. 
 	* XML is a self descriptive language. 
-->

<studentRecords xmlns="http://www.example.com/studentRecords" xmlns:xsi="http://www.example.com/studentRecordsSchema-instance" xsi:schemaLocation="http://www.example.com/studentRecords studentRecordsSchema.xsd">
	<student status="active">
		<name>Rahul</name>
		<age>18</age>
		<id>2553</id>
		<contact>012345</contact>
	</student>
	<student status="inactive">
		<name>Rajesh</name>
		<age>21</age>
		<id>2423</id>
		<contact>056751</contact>
	</student>
</studentRecords>
